// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7VQzI7KNpmBiGp1SyzSt8b94K3Jaa-cQ',
    appId: '1:965072541471:web:faa87801cf449e72dfc22a',
    messagingSenderId: '965072541471',
    projectId: 'movietre',
    authDomain: 'movietre.firebaseapp.com',
    storageBucket: 'movietre.firebasestorage.app',
    measurementId: 'G-RL1K49J6LS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEgvKVwHMMEfaC7Y7LLYBvl5GGOTAHCzo',
    appId: '1:965072541471:android:6d1690331c4e256adfc22a',
    messagingSenderId: '965072541471',
    projectId: 'movietre',
    storageBucket: 'movietre.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXSJg7roCBFONMcuSliaJKdkklPCoOchA',
    appId: '1:965072541471:ios:f526cf3daae658d5dfc22a',
    messagingSenderId: '965072541471',
    projectId: 'movietre',
    storageBucket: 'movietre.firebasestorage.app',
    iosBundleId: 'com.example.movietre',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXSJg7roCBFONMcuSliaJKdkklPCoOchA',
    appId: '1:965072541471:ios:f526cf3daae658d5dfc22a',
    messagingSenderId: '965072541471',
    projectId: 'movietre',
    storageBucket: 'movietre.firebasestorage.app',
    iosBundleId: 'com.example.movietre',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7VQzI7KNpmBiGp1SyzSt8b94K3Jaa-cQ',
    appId: '1:965072541471:web:b416b7fce76823f5dfc22a',
    messagingSenderId: '965072541471',
    projectId: 'movietre',
    authDomain: 'movietre.firebaseapp.com',
    storageBucket: 'movietre.firebasestorage.app',
    measurementId: 'G-RVBTH9F130',
  );
}
